import YoutubeIco from "./component/YoutubeIco.js"
import OtherIco from "./component/OtherIco.js"
import YoutubeCards from "./component/YoutubeCards.js"
import OtherCards from "./component/OtherCards.js"
import { AnimatePresence } from "framer-motion"
import SlideHr from "/components/animation/slideHorizontally"

import { useState } from "react"
import Head from "next/head"
export default function blogPage(){

const [state, setstate] = useState("youtube");

          return(
                    <div className="bg-gray-100 max-w-full max-h-screen md:mx-auto lg:w-8/12 md:w-10/12">
                     
                     <Head>
                            <title>Terran Kartik Tellus | Recommendations</title>
                            <meta name="description" content="Generated by create next app" />
                            <link rel="icon" href="/svg/favicon.svg" />
                      
                         </Head>

                     <div className="max-w-full ">
                        
                        <div class="w-screen flex  flex-col ">
                              <div class="w-screen  flex overflow-x-scroll hide-scroll-bar ">
                                  <div class="w-screen flex justify-start pt-6 pb-28  flex-nowrap  px-24 sm:px-48 md:px-60 lg:px-96">
                                       <div onClick={()=>(setstate("youtube"))} class="cursor-pointer hover: block ">
                                           <div  class="py-1 px-1 max-w-xs overflow-hidden rounded-lg shadow-md bg-white hover:shadow-2xl transition-shadow duration-300 ease-in-out">
                                                <YoutubeIco />
                                           </div>
                                       </div>
                                       <div onClick={()=>(setstate("other"))} class="cursor-pointer hover: block ml-20 ">
                                           <div onClick={()=>(setstate("other"))} class="py-1 px-1 max-w-xs overflow-hidden rounded-lg shadow-md bg-white hover:shadow-2xl transition-shadow duration-300 ease-in-out">
                                                <OtherIco />
                                           </div>
                                       </div>   
                                       
                                  </div>
                              
                              </div>
                        <div className="overflow-hidden mt-5 w-8/12 flex-nowrap">
                        {
                          state=="youtube" && <SlideHr initialOpacity={0} animateOpacity={1} exitOpacity={1} animateDelay={0.2} animateDuration={0.25} initialLocation={100} animateLocation={0} exitLocation={0}>
                            <AnimatePresence><YoutubeCards /></AnimatePresence>
                          </SlideHr>

                        }{  
                          state=="other" && <SlideHr initialOpacity={0} animateOpacity={1} exitOpacity={1} animateDelay={0.2} animateDuration={0.25} initialLocation={100} animateLocation={0} exitLocation={-100}>
                            <AnimatePresence><OtherCards /></AnimatePresence>
                         </SlideHr>
                        }
                        </div>
                        </div>

                    
                    </div>
                   
                    </div>
          );
}

