import Head from 'next/head'
import Scale from "/components/animation/scale"
import SlideVr from "/components/animation/slideVertically";
import SlideHr from "/components/animation/slideHorizontally";
import { useEffect,useState } from 'react';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Terran Kartik Tellus | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/svg/favicon.svg" />
      </Head>
    
    <div className="m-0 font-OpenSans bg-neutral-900 ">
      
      <div ><Body /></div>
    </div>
    
    </div>
  )
}


function Body(){
  
  


  return(
   <div className=" w-screen bg-transparent flex justify-center   ">  
    <div className="flex flex-col  items-center    w-10/12 md:w-3/6 ">
      
      <div className="flex flex-col items-center text-slate-100 mt-12">
        <SlideVr initialOpacity={0} animateOpacity={1} exitOpacity={1} animateDelay={0.4} animateDuration={0.5} initialLocation={40} animateLocation={0} exitLocation={0}>
        <Scale initialScale={0.8} animateScale={1} exitScale={0.8} animateDelay={0.5} animateDuration={1} >
        <div className="w-16 h-16 md:w-32 md:h-40"><img className="scale-95 hover:scale-105 hover:opacity-100 transition-transform duration-300" src="/svg/myLogo.svg" /></div>
        </Scale>
        </SlideVr>

        <SlideHr initialOpacity={0} animateOpacity={1} exitOpacity={1} animateDelay={0.6} animateDuration={0.5} initialLocation={40} animateLocation={0} exitLocation={0}>
        <SlideVr initialOpacity={0} animateOpacity={1} exitOpacity={1} animateDelay={0.6} animateDuration={0.5} initialLocation={40} animateLocation={0} exitLocation={0}>
        <div className=" text-slate-100 font-semibold text-2xl md:text-4xl tracking-widest       hover:text-white  hover:scale-105 hover:opacity-100 transition-transform duration-700">Terran Kartik Tellus</div>
        </SlideVr>
        </SlideHr>
        
        <SlideHr initialOpacity={0} animateOpacity={1} exitOpacity={1} animateDelay={0.6} animateDuration={0.5} initialLocation={-40} animateLocation={0} exitLocation={0}>
        <SlideVr initialOpacity={0} animateOpacity={1} exitOpacity={1} animateDelay={0.6} animateDuration={0.5} initialLocation={40} animateLocation={0} exitLocation={0}>
        <div className="text-slate-100 font-normal text-xs md:text-sm mt-1 tracking-normal md:tracking-widest hover:text-white  md:scale-105 hover:opacity-100 transition-transform duration-700">Designer : Developer : STEM Enthusiast</div>      
        </SlideVr>
        </SlideHr>
      
      
      </div>
      
      <div className="mb-4 pb-4 flex-grow">
      <Scale initialScale={1.2} animateScale={0.9} exitScale={0.8} animateDelay={0.7} animateDuration={1} >
      <SlideVr initialOpacity={0} animateOpacity={1} exitOpacity={1} animateDelay={0.7} animateDuration={0.5} initialLocation={40} animateLocation={0} exitLocation={0}>
      <BottomLayer />
      </SlideVr>
      </Scale>
      </div>

     <div className=" text-white pt-10 ">
      <div>About</div>
      <div>Work</div>
      <div>Blog</div>
      <div>Contact</div>
     </div>
    </div>
   </div>
  );
}

function BottomLayer(){
  return(
      <div className="mt-36 space-x-2 md:mt-44 flex flex-row h-20 w-11/12  text-slate-200 justify-center">
        <div className="mr-4 md:mr-0 pr-2 grid grid-rows-3 gap-0 text-right w-1/3 ">
              <div className=" col-span-2 "><img className="ml-auto h-6 w-7" src="./svg/man.svg" /></div>
              <div className=" col-span-2 mt-1 text-sm font-semibold">Title</div>
              <div className=" col-span-2 text-xs font-normal ">Creative entrepreneur</div>
            </div>

        <div className=" hidden md:block ">
            <div className=" grid grid-rows-3 gap-x-9 gap text-center">
              <div className=" col-span-2 "><img className="mx-auto h-6 w-7" src="./svg/location.svg" /></div>
              <div className=" col-span-2 mt-1 text-sm font-semibold text-clip">South-Asia</div>
              <div className=" col-span-2 text-xs font-normal ">Mumbai : Hong Kong</div>
            </div>
        </div>

        <div className="w-1/3 pl-2 grid grid-rows-3 gap-0 text-left ">
              <div className=" col-span-2 "><img className="mr-auto h-6 w-7" src="./svg/email.svg" /></div>
              <div className=" col-span-2 mt-1 text-sm font-semibold">Email</div>
              <div className=" col-span-2 text-xs font-normal ">TerranKartikTellus<br/>@gmail.com</div>
        </div>

      </div>
  );
}