import Head from 'next/head'
import Body from "/components/pages/home/body"



export default function Home() {
  return (
    
    <div className="">
      
      <Head>
        <title>Terran Kartik Tellus | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/svg/favicon.svg" />
      </Head>
    
    
      <div className="m-0 font-OpenSans bg-neutral-900 "> 
        <div ><Body /></div>
      </div>
    </div>
  
  )
}

